name: CL_spine_7T_env_py9
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - acres=0.5.0=pyhd8ed1ab_0
  - astor=0.8.1=pyhd8ed1ab_1
  - bids-validator=1.14.7.post0=pyhd8ed1ab_1
  - bidsschematools=1.1.2=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h6a678d5_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - ci-info=0.3.0=pyhd8ed1ab_0
  - click=8.1.7=py39h06a4308_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.13.18=hb2f20db_0
  - dcm2bids=3.2.0=pyhd8ed1ab_1
  - docopt=0.6.2=pyhd8ed1ab_2
  - expat=2.6.2=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py39h5eee18b_0
  - formulaic=1.1.1=pyhd8ed1ab_0
  - freetype=2.12.1=h4a9f257_0
  - frozendict=2.3.2=py39hb9d737c_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - glib=2.69.1=h4ff587b_1
  - graphlib-backport=1.0.3=pyhd8ed1ab_0
  - greenlet=1.1.2=py39h5a03fae_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - interface_meta=1.3.0=pyhd8ed1ab_1
  - isodate=0.6.1=py39h06a4308_0
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_2
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=ha637b67_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm14=14.0.6=hef93074_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - libxslt=1.1.37=h5eee18b_1
  - looseversion=1.3.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.8.4=py39h06a4308_0
  - matplotlib-base=3.8.4=py39h1128e8f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mysql=5.7.24=he378463_2
  - ncurses=6.4=h6a678d5_0
  - networkx=3.2.1=py39h06a4308_0
  - nibabel=5.2.1=pyha770c72_0
  - nilearn=0.10.4=pyhd8ed1ab_0
  - nipype=1.8.6=py39hf3d152e_0
  - num2words=0.5.14=pyhe01879c_0
  - numexpr=2.8.4=py39he184ba9_0
  - numpy=1.24.3=py39h14f4228_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=1.1.1w=h7f8727e_0
  - packaging=24.1=py39h06a4308_0
  - pandas=2.2.2=py39h6a678d5_0
  - pcre=8.45=h295c915_0
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - pooch=1.7.0=py39h06a4308_0
  - pybids=0.20.0=pyhd8ed1ab_0
  - pydicom=2.4.4=pyhd8ed1ab_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.0=hdb3f193_2
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2024.1=py39h06a4308_0
  - qt-main=5.15.2=h110a718_10
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - seaborn=0.13.2=py39h06a4308_0
  - setuptools=69.5.1=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlalchemy=2.0.43=py39h7e39e78_0
  - sqlite=3.45.3=h5eee18b_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.4.1=py39h5eee18b_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - universal_pathlib=0.2.6=pyhd8ed1ab_1
  - urllib3=2.2.2=py39h06a4308_0
  - wheel=0.43.0=py39h06a4308_0
  - wrapt=1.14.1=py39hb9d737c_0
  - xvfbwrapper=0.2.9=pyhd8ed1ab_1005
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.16.0
      - comm==0.2.2
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - etelemetry==0.3.1
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - importlib-metadata==8.2.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - lxml==5.2.2
      - markupsafe==2.1.5
      - matlabengine==9.11.23
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - prov==2.0.1
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydot==3.0.1
      - pygments==2.18.0
      - python-json-logger==2.0.7
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - rdflib==6.3.2
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.19.1
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - send2trash==1.8.3
      - simplejson==3.19.2
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.3.0
      - traitlets==5.14.3
      - traits==6.3.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - zipp==3.19.2
prefix: /export02/data/landelle/anaconda/envs/CL_spine_7T_env_py9
